version: '3.4'
services:
  tickets:
    image: tickets
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    command: mvn spring-boot:run